#!/bin/bash
iser=$(cat /root/.isp)
if [[ $iser -gt 0 ]]; then
curl "ipinfo.io/org?token=93c227d86a3c9f" > /root/.isp
else
echo ""
fi

iser1=$(cat /root/.city)
if [[ $iser -gt 0 ]]; then
curl "ipinfo.io/org?token=93c227d86a3c9f" > /root/.city
else
echo ""
fi
